styles:
    inputs:
        - 'bundles/ibnabsaad/scss/settings/global-settings'
        - 'bundles/ibnabsaad/scss/variables/product-sticker-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/primary-menu-config.scss'
        - 'bundles/ibnabsaad/scss/variables/main-menu-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/embedded-list/embedded-list-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/embedded-list/embedded-list-slider-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/top-bar-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/information-nav-config.scss'
        - 'bundles/ibnabsaad/scss/styles.scss'
    output: 'css/styles.css'