styles:
    inputs:
        #- 'bundles/ibnabsaad/themes/vendors/slick/slick.css'
        - 'bundles/ibnabsaad/themes/oro/scss/settings/global-settings.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/base-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/breadcrumbs-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/link-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/page-title-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/page-subtitle-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/page-main-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/page-container-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/page-content-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/page-header-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/page-footer-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/page-sidebar-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/copyright-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/section-title-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/notifications-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/primary-menu-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/notification-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/notification-flash-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/loader-mask-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/embedded-list/embedded-list-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/embedded-list/embedded-list-slider-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/ui/dialog-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/settings/sizes.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/main-menu-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/top-bar-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/information-nav-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/variables/product-sticker-config.scss'
        - 'bundles/ibnabsaad/themes/oro/scss/styles.scss'
    output: 'css/layout/default/styles.css'
