styles:
    - bundles/ibnabsaad/themes/oro/css/style.css
label: Saad Theme
icon: bundles/ibnabsaad/themes/oro/images/favicon.ico
logo: bundles/ibnabsaad/themes/oro/images/logo.png
screenshot: bundles/ibnabsaad/themes/oro/images/screenshot.png
